# -*- coding: utf-8 -*-
"""Unemployment Analysis with Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15IGrv3f4mxkQssAns9y7sBa60HV3qrI9
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Machine learning tools
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

df = pd.read_csv("/content/Unemployment in India.csv")

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
print("✅ Columns after cleaning:", df.columns.tolist())

print(df.head())

print(df.shape)

df.dtypes

print(df.isnull().sum())

print(df['Region'].value_counts())

df.isnull().sum()

df.duplicated().sum()

df.columns.to_list()

print("First 5 rows:")
print(df.head())
print("\nColumns:", df.columns)

print('row count =>',df.shape[0])
print('column count =>',df.shape[1])

print(df.describe())

df_selected_col = list(df.select_dtypes("object").columns)
df_selected_col = list(df.select_dtypes("object").columns)

for col in df_selected_col:
  print(f"Categories in {col} column...")
  print(df[col].unique(), end="\n\n")

print("\nMissing values before cleaning:\n", df.isnull().sum())
print("\nDuplicated rows:", df.duplicated().sum())

date_col = " Date"   # note: there is a leading space in the column name
rate_col = " Estimated Unemployment Rate (%)"

df[date_col] = pd.to_datetime(df[date_col], errors="coerce")

df[rate_col] = pd.to_numeric(df[rate_col], errors="coerce")

print(df.head())

print("Columns after cleaning:", df.columns)

date_col = "Date"
rate_col = "Estimated Unemployment Rate (%)"

monthly = df[[rate_col]].resample("M").mean()

plt.figure(figsize=(12,5))
plt.plot(monthly.index, monthly[rate_col], label="Unemployment Rate")
plt.axvspan(pd.to_datetime("2020-03-01"), pd.to_datetime("2021-12-31"),
            color="red", alpha=0.2, label="COVID Period")
plt.title("Unemployment Rate in India (Monthly)")
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.legend()
plt.grid(True)
plt.show()

covid_start = pd.Timestamp("2020-03-01")
covid_end = pd.Timestamp("2021-12-31")

pre_mean = monthly.loc[monthly.index < covid_start, rate_col].mean()
during_mean = monthly.loc[(monthly.index >= covid_start) & (monthly.index <= covid_end), rate_col].mean()
post_mean = monthly.loc[monthly.index > covid_end, rate_col].mean()

print("\nAverage Unemployment Rate:")

print(f"- Pre-COVID: {pre_mean:.2f}%")

print(f"- During COVID: {during_mean:.2f}%")

print(f"- Post-COVID: {post_mean:.2f}%")

monthly["month"] = monthly.index.month
seasonal = monthly.groupby("month")[rate_col].mean()

plt.figure(figsize=(10,4))
plt.plot(seasonal.index, seasonal.values, marker="o")
plt.title("Average Unemployment Rate by Month (Seasonal Pattern)")
plt.xlabel("Month (1=Jan)")
plt.ylabel("Unemployment Rate (%)")
plt.grid(True)
plt.show()

monthly["year"] = monthly.index.year
yearly = monthly.groupby("year")[rate_col].mean()

plt.figure(figsize=(10,4))
plt.plot(yearly.index, yearly.values, marker="o")
plt.title("Yearly Average Unemployment Rate")
plt.xlabel("Year")
plt.ylabel("Unemployment Rate (%)")
plt.grid(True)
plt.show()

monthly["diff"] = monthly[rate_col].diff()
print("\nTop 5 monthly increases:")

print(monthly["diff"].nlargest(5))

print("\nTop 5 monthly decreases:")
print(monthly["diff"].nsmallest(5))

print(df.columns.tolist())
# Clean column names first
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
# Check again
print(df.columns.tolist())

